// Checked final patch for archive-generated runtime source.
const edits: [string,string,string][] = [
  [
    "database.ts",
    "export async function updateReservation(id: string, patch: Partial<Reservation>): Promise<Reservation | null> {\n  const cur = await kv.get<Reservation>(toKey(\"reservation\", id));\n  const prev = cur.value;\n  if (!prev) return null;\n\n  const next: Reservation = {\n    ...prev,\n    // לא לדרוס שדות שלא הגיעו\n    restaurantId: patch.restaurantId ?? prev.restaurantId,\n    date: patch.date ?? prev.date,\n    time: patch.time ?? prev.time,\n    people: patch.people ?? prev.people,\n    note: patch.note ?? prev.note,\n    status: patch.status ?? prev.status,\n    firstName: patch.firstName ?? prev.firstName,\n    lastName: patch.lastName ?? prev.lastName,\n    phone: patch.phone ?? prev.phone,\n    durationMinutes: patch.durationMinutes ?? prev.durationMinutes,\n    preferredLayoutId: patch.preferredLayoutId ?? prev.preferredLayoutId,\n    userId: patch.userId ?? prev.userId,\n    createdAt: prev.createdAt,\n  };\n\n  const tx = kv.atomic().set(toKey(\"reservation\", id), next);\n\n  // אם restaurantId או date השתנו — לעדכן אינדקס reservation_by_day\n  const dayChanged = (next.restaurantId !== prev.restaurantId) || (next.date !== prev.date);\n  if (dayChanged) {\n    tx.delete(toKey(\"reservation_by_day\", prev.restaurantId, prev.date, id))\n      .set(toKey(\"reservation_by_day\", next.restaurantId, next.date, id), 1);\n  }\n\n  // אם userId השתנה — לעדכן אינדקס reservation_user\n  if (next.userId !== prev.userId) {\n    if (prev.userId) tx.delete(toKey(\"reservation_user\", prev.userId, id));\n    if (next.userId) tx.set(toKey(\"reservation_user\", next.userId, id), 1);\n  }\n\n  const res = await tx.commit();\n  if (!res.ok) throw new Error(\"update_reservation_race\");\n  return next;\n}\n\n",
    "async function updateReservationAtomic(\n  id: string,\n  merge: (previous: Reservation) => Reservation,\n): Promise<Reservation | null> {\n  for (let attempt = 0; attempt < 10; attempt++) {\n    const cur = await kv.get<Reservation>(toKey(\"reservation\", id));\n    const prev = cur.value;\n    if (!prev) return null;\n    const next = { ...merge(prev), id: prev.id, createdAt: prev.createdAt };\n    const tx = kv.atomic().check(cur).set(toKey(\"reservation\", id), next);\n    if (next.restaurantId !== prev.restaurantId || next.date !== prev.date) {\n      tx.delete(toKey(\"reservation_by_day\", prev.restaurantId, prev.date, id))\n        .set(toKey(\"reservation_by_day\", next.restaurantId, next.date, id), 1);\n    }\n    if (next.userId !== prev.userId) {\n      if (prev.userId) tx.delete(toKey(\"reservation_user\", prev.userId, id));\n      if (next.userId) tx.set(toKey(\"reservation_user\", next.userId, id), 1);\n    }\n    // Invalidate any in-flight createReservationSafe capacity snapshot.\n    tx.set(toKey(\"reservation_day_lock\", prev.restaurantId, prev.date), Date.now());\n    if (next.restaurantId !== prev.restaurantId || next.date !== prev.date) {\n      tx.set(toKey(\"reservation_day_lock\", next.restaurantId, next.date), Date.now());\n    }\n    if ((await tx.commit()).ok) return next;\n  }\n  throw new Error(\"update_reservation_race\");\n}\n\nexport async function updateReservation(id: string, patch: Partial<Reservation>): Promise<Reservation | null> {\n  return await updateReservationAtomic(id, (prev) => {\n  const next: Reservation = {\n    ...prev,\n    // לא לדרוס שדות שלא הגיעו\n    restaurantId: patch.restaurantId ?? prev.restaurantId,\n    date: patch.date ?? prev.date,\n    time: patch.time ?? prev.time,\n    people: patch.people ?? prev.people,\n    note: patch.note ?? prev.note,\n    status: patch.status ?? prev.status,\n    firstName: patch.firstName ?? prev.firstName,\n    lastName: patch.lastName ?? prev.lastName,\n    phone: patch.phone ?? prev.phone,\n    durationMinutes: patch.durationMinutes ?? prev.durationMinutes,\n    preferredLayoutId: patch.preferredLayoutId ?? prev.preferredLayoutId,\n    userId: patch.userId ?? prev.userId,\n    createdAt: prev.createdAt,\n  };\n\n    return next;\n  });\n}\n\n"
  ],
  [
    "database.ts",
    "export async function updateReservationFields(id: string, patch: Partial<Reservation>): Promise<Reservation | null> {\n  const cur = await kv.get<Reservation>(toKey(\"reservation\", id));\n  if (!cur.value) return null;\n  const merged = { ...cur.value, ...patch };\n  await kv.set(toKey(\"reservation\", id), merged);\n  // אם עבר יום/מסעדה — עדכן אינדקס\n  if (patch.restaurantId || patch.date) {\n    const prev = cur.value;\n    const next = merged as Reservation;\n    if (prev.restaurantId !== next.restaurantId || prev.date !== next.date) {\n      const tx = kv.atomic()\n        .delete(toKey(\"reservation_by_day\", prev.restaurantId, prev.date, id))\n        .set(toKey(\"reservation_by_day\", next.restaurantId, next.date, id), 1);\n      await tx.commit().catch(() => {});\n    }\n  }\n  return merged as Reservation;\n}\n\n",
    "export async function updateReservationFields(id: string, patch: Partial<Reservation>): Promise<Reservation | null> {\n  // Undefined means omitted; an arrival without a new note must preserve the old note.\n  const defined = Object.fromEntries(Object.entries(patch).filter(([, value]) => value !== undefined));\n  return await updateReservationAtomic(id, (previous) => ({ ...previous, ...defined }));\n}\n\n"
  ]
];
for (const [path, before, after] of edits) {
 const source = await Deno.readTextFile(path);
 if (source.includes(after)) continue;
 if (source.split(before).length !== 2) throw Error(`Missing or ambiguous patch: ${path}`);
 await Deno.writeTextFile(path, source.replace(before, after));
}
