const edits: [string,string,string][] = [
  [
    "inventory/inventory_db.ts",
    "export async function applyInventoryTx(params: {\n  restaurantId: string;\n  ingredientId: string;\n  type: InventoryTxType;\n  deltaQty: number;\n  costTotal?: number;\n  reason?: string;\n}): Promise<{ ingredient: Ingredient; tx: InventoryTx }> {\n  const ingKey = kIngredient(params.restaurantId, params.ingredientId);\n  const row = await kv.get<Ingredient>(ingKey);\n  if (!row.value) throw new Error(\"ingredient_not_found\");\n\n  const ing = row.value;\n  const now = Date.now();\n\n  const newQty = (ing.currentQty ?? 0) + params.deltaQty;\n\n  let nextCostPerUnitAuto = ing.costPerUnitAuto;\n  let nextCostAutoUpdatedAt = ing.costAutoUpdatedAt;\n\n  // AUTO cost update from deliveries with cost + qty\n  if (\n    params.type === \"delivery\" &&\n    typeof params.costTotal === \"number\" &&\n    Number.isFinite(params.costTotal) &&\n    params.costTotal >= 0 &&\n    Number.isFinite(params.deltaQty) &&\n    params.deltaQty > 0\n  ) {\n    const unitCost = params.costTotal / params.deltaQty;\n\n    if (typeof nextCostPerUnitAuto === \"number\" && Number.isFinite(nextCostPerUnitAuto)) {\n      nextCostPerUnitAuto = (nextCostPerUnitAuto * 0.7) + (unitCost * 0.3);\n    } else {\n      nextCostPerUnitAuto = unitCost;\n    }\n    nextCostAutoUpdatedAt = now;\n  }\n\n  const updated: Ingredient = {\n    ...ing,\n    currentQty: newQty,\n    costPerUnitAuto: nextCostPerUnitAuto,\n    costAutoUpdatedAt: nextCostAutoUpdatedAt,\n    updatedAt: now,\n  };\n\n  const tx: InventoryTx = {\n    id: crypto.randomUUID(),\n    restaurantId: params.restaurantId,\n    ingredientId: params.ingredientId,\n    type: params.type,\n    deltaQty: params.deltaQty,\n    newQty,\n    costTotal: params.costTotal,\n    reason: params.reason,\n    createdAt: now,\n  };\n\n  const atomic = kv.atomic()\n    .set(ingKey, updated)\n    .set(kInvTx(params.restaurantId, tx.id), tx);\n\n  const res = await atomic.commit();\n  if (!res.ok) throw new Error(\"inventory_tx_failed\");\n\n  return { ingredient: updated, tx };\n}\n\n",
    "export async function applyInventoryTx(params: {\n  restaurantId: string;\n  ingredientId: string;\n  type: InventoryTxType;\n  deltaQty: number;\n  costTotal?: number;\n  reason?: string;\n}): Promise<{ ingredient: Ingredient; tx: InventoryTx }> {\n  if (!Number.isFinite(params.deltaQty) || params.deltaQty === 0 ||\n      ![\"delivery\", \"adjustment\", \"consumption\", \"waste\"].includes(params.type) ||\n      (params.costTotal !== undefined && (!Number.isFinite(params.costTotal) || params.costTotal < 0))) {\n    throw new Error(\"invalid_inventory_tx\");\n  }\n  for (let attempt = 0; attempt < 10; attempt++) {\n  const ingKey = kIngredient(params.restaurantId, params.ingredientId);\n  const row = await kv.get<Ingredient>(ingKey);\n  if (!row.value) throw new Error(\"ingredient_not_found\");\n\n  const ing = row.value;\n  const now = Date.now();\n\n  const newQty = (ing.currentQty ?? 0) + params.deltaQty;\n  if (!Number.isFinite(newQty)) throw new Error(\"invalid_inventory_quantity\");\n\n  let nextCostPerUnitAuto = ing.costPerUnitAuto;\n  let nextCostAutoUpdatedAt = ing.costAutoUpdatedAt;\n\n  // AUTO cost update from deliveries with cost + qty\n  if (\n    params.type === \"delivery\" &&\n    typeof params.costTotal === \"number\" &&\n    Number.isFinite(params.costTotal) &&\n    params.costTotal >= 0 &&\n    Number.isFinite(params.deltaQty) &&\n    params.deltaQty > 0\n  ) {\n    const unitCost = params.costTotal / params.deltaQty;\n\n    if (typeof nextCostPerUnitAuto === \"number\" && Number.isFinite(nextCostPerUnitAuto)) {\n      nextCostPerUnitAuto = (nextCostPerUnitAuto * 0.7) + (unitCost * 0.3);\n    } else {\n      nextCostPerUnitAuto = unitCost;\n    }\n    nextCostAutoUpdatedAt = now;\n  }\n\n  const updated: Ingredient = {\n    ...ing,\n    currentQty: newQty,\n    costPerUnitAuto: nextCostPerUnitAuto,\n    costAutoUpdatedAt: nextCostAutoUpdatedAt,\n    updatedAt: now,\n  };\n\n  const tx: InventoryTx = {\n    id: crypto.randomUUID(),\n    restaurantId: params.restaurantId,\n    ingredientId: params.ingredientId,\n    type: params.type,\n    deltaQty: params.deltaQty,\n    newQty,\n    costTotal: params.costTotal,\n    reason: params.reason,\n    createdAt: now,\n  };\n\n  const atomic = kv.atomic().check(row)\n    .set(ingKey, updated)\n    .set(kInvTx(params.restaurantId, tx.id), tx);\n\n  const res = await atomic.commit();\n  if (!res.ok) continue;\n\n  return { ingredient: updated, tx };\n  }\n  throw new Error(\"inventory_tx_conflict\");\n}\n\n"
  ],
  [
    "inventory/inventory_db.ts",
    "export async function markPurchaseOrderDelivered(params: {\n  restaurantId: string;\n  poId: string;\n}): Promise<PurchaseOrder | null> {\n  const key = kPO(params.restaurantId, params.poId);\n  const row = await kv.get<PurchaseOrder>(key);\n  if (!row.value) return null;\n\n  const po = row.value;\n  if (po.status === \"delivered\" || po.status === \"cancelled\") return po;\n\n  // Validate ingredient existence first\n  for (const ln of po.lines || []) {\n    if (!ln.ingredientId) continue;\n    const ing = await getIngredient(params.restaurantId, ln.ingredientId);\n    if (!ing) {\n      throw new Error(`po_missing_ingredient:${ln.ingredientId}`);\n    }\n  }\n\n  // Create delivery tx per line\n  for (const ln of po.lines || []) {\n    const qty = Number(ln.qty || 0);\n    if (!ln.ingredientId || !(qty > 0)) continue;\n\n    await applyInventoryTx({\n      restaurantId: params.restaurantId,\n      ingredientId: ln.ingredientId,\n      type: \"delivery\",\n      deltaQty: qty,\n      reason: `PO ${po.id} delivered (supplier=${po.supplierNameSnapshot})`,\n    });\n  }\n\n  const now = Date.now();\n  const updated: PurchaseOrder = {\n    ...po,\n    status: \"delivered\",\n    deliveredAt: now,\n    updatedAt: now,\n  };\n\n  const ok = await kv.atomic().check(row).set(key, updated).commit();\n  if (!ok.ok) return null;\n  return updated;\n}\n",
    "export async function markPurchaseOrderDelivered(params: {\n  restaurantId: string;\n  poId: string;\n  actor?: string;\n}): Promise<PurchaseOrder | null> {\n  const key = kPO(params.restaurantId, params.poId);\n  for (let attempt = 0; attempt < 10; attempt++) {\n    const row = await kv.get<PurchaseOrder>(key);\n    if (!row.value) return null;\n    const po = row.value;\n    if (po.status === \"delivered\" || po.status === \"cancelled\") return po;\n    // Aggregate repeated ingredients so each stock row is written once.\n    const quantities = new Map<string, number>();\n    for (const line of po.lines || []) {\n      const qty = Number(line.qty);\n      if (!line.ingredientId || !Number.isFinite(qty) || qty <= 0) {\n        throw new Error(\"invalid_purchase_order_line\");\n      }\n      const total = (quantities.get(line.ingredientId) ?? 0) + qty;\n      if (!Number.isFinite(total)) throw new Error(\"invalid_purchase_order_line\");\n      quantities.set(line.ingredientId, total);\n    }\n    const timestamp = Date.now();\n    const updated: PurchaseOrder = { ...po, status: \"delivered\", deliveredAt: timestamp, updatedAt: timestamp };\n    const atomic = kv.atomic().check(row).set(key, updated);\n    for (const [ingredientId, qty] of quantities) {\n      const ingredientKey = kIngredient(params.restaurantId, ingredientId);\n      const stock = await kv.get<Ingredient>(ingredientKey);\n      if (!stock.value) throw new Error(`po_missing_ingredient:${ingredientId}`);\n      const newQty = (stock.value.currentQty ?? 0) + qty;\n      if (!Number.isFinite(newQty)) throw new Error(\"invalid_inventory_quantity\");\n      const movement: InventoryTx = {\n        id: crypto.randomUUID(), restaurantId: params.restaurantId,\n        ingredientId, type: \"delivery\", deltaQty: qty, newQty,\n        reason: `PO ${po.id} delivered (supplier=${po.supplierNameSnapshot})`,\n        createdAt: timestamp,\n      };\n      atomic.check(stock)\n        .set(ingredientKey, { ...stock.value, currentQty: newQty, updatedAt: timestamp })\n        .set(kInvTx(params.restaurantId, movement.id), movement);\n    }\n    // Stock, ledger and receipt status either all commit or none do.\n    if ((await atomic.commit()).ok) return updated;\n  }\n  throw new Error(\"purchase_order_delivery_conflict\");\n}\n"
  ]
];
for (const [path,before,after] of edits) {
 const source=await Deno.readTextFile(path);
 if(source.includes(after)) continue;
 if(source.split(before).length!==2) throw Error(`Missing or ambiguous patch: ${path}`);
 await Deno.writeTextFile(path,source.replace(before,after));
}
